import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

import "./globals.css";
import { Bricolage_Grotesque } from 'next/font/google'

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolage.className} h-full antialiased`}
    >
      <body className={` ${bricolage.className} min-h-full flex flex-col`}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
